### ISSUE TITLE
Python not compiling

### ISSUE THREAD

**Issue by prithvirajkadiyala** [kipr/botui#41]
Might be where it is pointing to.

Will try running code in Python IDLE for more information.

Python IDLE works fine for programs without importing wallaby.

As soon as we import wallaby I get the following error:
`
>import wallaby
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wallaby.py", line 28, in <module>
    _wallaby = swig_import_helper()
  File "wallaby.py", line 24, in swig_import_helper
    _mod = imp.load_module('_wallaby', fp, pathname, description)
ImportError: dynamic module does not define init function (init_wallaby)
`

Can it be an issue with the SWIG file generation maybe?
I initialized Wombat on the same paths as that of Wallaby.
`
>>> import sys
>>> sys.path
['', '/home/pi', '/usr/lib', '/home/root', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-arm-linux-gnueabihf', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
`

**Comment by prithvirajkadiyala** [comment]
Had Issue in the Libwallaby CMakeLists.txt where it did not mention the version of the Python to be used for compiling the code.
Changed it to use Python2.7 specifically and now it is able to use the module wallaby and run programs as desired on the Kiss-IDE

Issue still persists with running a python program on the Wombat.
Issue should be somewhere in the Compiler of the BOTUI

**Comment by prithvirajkadiyala** [comment]
With the recent update it seems like Python isn't able to point to the right DLL file (libwallaby.so)
Because of which we are having to go around with the cdll import like the following
```
import ctypes
  KIPR = ctypes.CDLL("/usr/lib/libwallaby.so")
```
